### ISSUE TITLE
Links in the table of contents of the example notebooks do not work

### ISSUE THREAD

**Issue by rusty-electron** [bayesflow-org/bayesflow#144]
* The recent commit 162a616c0267839998588e547ce34aa3bb966c91 adds TOC to all the example notebooks in https://github.com/stefanradev93/BayesFlow/tree/master/examples
* The TOC links work well within the jupyter notebooks (even in VScode notebook mode). But it appears that when the notebook is rendered by sphinx (for the website), it generates additional anchor links for its own TOC list and this breaks the TOC links embedded in the jupyter notebook.

**Comment by paul-buerkner** [comment]
Note to devs: we will need to check this before merging dev into main.
