### ISSUE TITLE
Further improve CompositeSimulator

### ISSUE THREAD

**Issue by paul-buerkner** [bayesflow-org/bayesflow#198]
I think the CompositeSimulator has an excellent design. To further improve user-friendliness I suggest the following two changes:

(1) Rename to `SequentialSimulator`. I think this is a more descriptive name.

(2) Merge `CompositeSimulator` and `CompositeLambdaSimulator` into one function (`SequentialSimulator`), which takes a list(?) of objects, each of which is coercible to a `Simulator` object. First, we go over the list of objects, transform each of them to a Simulator (if it is not already one), and then execute the code currently implemented in `CompositeSimulator`. This way, users have a single interface for building sequential simulators, and can use any object which we deem valid to serve as a simulator.

**Comment by LarsKue** [comment]
To accommodate this, we will add a dispatch utility for simulators.
