### ISSUE TITLE
Flow matching with normal base distribution returns nan loss

### ISSUE THREAD

**Issue by maltelueken** [bayesflow-org/bayesflow#208]
When using a continuous approximator with flow matching plus set transformer (or deepset) and `base_distribution="normal"`, the loss becomes `nan` after two steps.

Is there anything that I missed to add MMD to the summary loss?

**Comment by marvinschmitt** [comment]
Thanks for reporting the issue. Could you please provide a minimal reproducible example, at least of the exact definitions of your networks?

**Comment by LarsKue** [comment]
Closing this as not reproducible.
