### ISSUE TITLE
Introduce better support for bypassing dispatch utils

### ISSUE THREAD

**Issue by LarsKue** [bayesflow-org/bayesflow#228]
Currently, a lot of networks use string-based dispatch for internal architectures, e.g. [Single Couplings internal subnet](https://github.com/bayesflow-org/bayesflow/blob/7ef3612074b3880db330b5d29d17c76e8c82b69a/bayesflow/networks/coupling_flow/couplings/single_coupling.py#L22). Ideally, we should allow users to always pass serializable keras objects too.

This comes at the cost of having to define a custom `from_config` and `get_config` method for each object that allows this, but it would make BayesFlow much more extensible from the outside.

**Comment by vpratz** [comment]
For the moment, we have decided to keep it limited to subnets, but if the need arises we will extend this to other arguments as well. If this is the case, we will discuss it in a new issue or reopen this one.
