### ISSUE TITLE
Diagnostic plots: Allow for custom names different from the dictionary keys

### ISSUE THREAD

**Issue by elseml** [bayesflow-org/bayesflow#257]
As far as I can see, currently all diagnostic functions that rely on the `preprocess()` function (e.g., `plot_recovery`, `plot_sbc_ecdf`) do not allow for custom `variable_names` (e.g., I may want to use `r"$\alpha$"` instead of `alpha` as the plot title).
This is caused by `preprocess` using the `dicts_to_arrays` function, in which `names` is used for filtering (relevant snippet of `dicts_to_arrays`):
```python
# Use user-provided names instead of inferred ones
names = list(post_variables.keys()) if names is None else names

post_variables = np.concatenate([v for k, v in post_variables.items() if k in names], axis=-1)
prior_variables = np.concatenate([v for k, v in prior_variables.items() if k in names], axis=-1)
```
Thus, passing custom `variable_names` leads to excluding the desired parameter instead of renaming it. 

I suggest that we clearly distinguish between the uses of names for **filtering** and **naming**. For example, we could have two arguments (names up for discussion) in the diagnostic plot functions:
- `filter_dict_keys`: Optional argument that can be used to filter the dict keys, such as how  `variable_names` is used at the moment.
- `variable_names`: Optional argument that can be used to pass custom parameter names for the plots (similar to `param_names` in BF1). I guess using a dict that assigns each key a custom name would be the safest option here to avoid mismatches due to filtering etc. I also like `param_names` from BF1 but I suppose this was changed to `variable_names` to be more generalizable?

Related to #235 @jerrymhuang.

**Comment by paul-buerkner** [comment]
I like your suggestions! and I agree that `variable_names` is better than `param_names` for BF2.

**Comment by stefanradev93** [comment]
Btw, this is somewhat critical, as we already have multiple use cases.

**Comment by paul-buerkner** [comment]
Okay, adding it to the BF 2.0 milestone then.
