### ISSUE TITLE
Passing of kwargs to inference network sample method

### ISSUE THREAD

**Issue by tobywise** [bayesflow-org/bayesflow#266]
First, thanks so much for your work on Bayesflow - it's great. 

On the `dev` branch, it's currently not possible to pass `kwargs` to the inference network `sample` method via the `approximator`. This would be useful, since some inference networks have important parameters set here (e.g., the `FlowMatching` network can have `n_steps` passed to `sample` which can be very useful). Any `kwargs` passed when `approximator.sample()` is called are currently passed only to the adapter.

This could be added by allowing separate kwargs for the adapter and inference network in `approximator.sample()` and passing these to the relevant methods, e.g.:

```python
    def sample(
        self,
        *,
        num_samples: int,
        conditions: dict[str, np.ndarray],
        adapter_kwargs: dict[str, Any] = None,
        sample_kwargs: dict[str, Any] = None,
    ) -> dict[str, np.ndarray]:
```

Or it may be better to instead restrict the use of additional arguments in the `_forward` / `_inverse` methods of the inference network and instead require these to be set when the class is instantiated, so that there's no need to pass `kwargs` when sampling?

Thanks!

**Comment by LarsKue** [comment]
Thank you for bringing this up. We have had a PR in progress that addresses this issue (#248), but it went under the radar. Can you check it out and see if this would fix your problems?

**Comment by vpratz** [comment]
Thanks for bringing this up again and testing the changes, they are now merged into `dev`.
